module.exports = {
  base: {
    contentWidth: 164,
    surface: 'goal-progress-stream',
    title: { top: 0, width: 164, height: 22 },
    history: { top: 30, width: 164, height: 34 },
    stream: { top: 72, width: 164 },
    titleSize: 15,
    historyTitleSize: 9,
    historySubSize: 7,
    metricHeight: 91,
    metricGap: 7,
    metricRadius: 16,
    metricPadding: 9,
    labelSize: 9,
    valueSize: 24,
    unitSize: 7,
    progressTextSize: 8,
    progressTrackHeight: 7,
    footerSize: 7,
    progressGap: 7
  },
  circle: {
    contentWidth: 136,
    title: { top: 14, width: 120, height: 22, circleFit: 'edges' },
    history: { top: 39, width: 136, height: 30, circleFit: 'center' },
    stream: { top: 74, width: 136, circleFit: 'none' },
    titleSize: 13,
    historyTitleSize: 8,
    historySubSize: 6,
    metricHeight: 86,
    metricGap: 6,
    metricRadius: 15,
    metricPadding: 8,
    labelSize: 8,
    valueSize: 22,
    unitSize: 6,
    progressTextSize: 7,
    progressTrackHeight: 6,
    footerSize: 6,
    progressGap: 5
  },
  pill: {
    contentWidth: 168,
    title: { top: 0, width: 168, height: 24 },
    history: { top: 32, width: 168, height: 42 },
    stream: { top: 82, width: 168 },
    titleSize: 17,
    historyTitleSize: 11,
    historySubSize: 9,
    metricHeight: 94,
    metricGap: 8,
    metricRadius: 18,
    metricPadding: 10,
    labelSize: 10,
    valueSize: 28,
    unitSize: 8,
    progressTextSize: 10,
    progressTrackHeight: 8,
    footerSize: 8,
    progressGap: 7
  },
  rect: { contentWidth: 164 }
}
