module.exports = {
  base: {
    contentWidth: 164,
    surface: 'calendar-dashboard',
    interaction: 'explicit-buttons',
    overflow: 'fixed',
    frame: { left: 14, top: 2, width: 164, height: 225 },
    summary: {
      header: { width: 164, height: 38 },
      date: { width: 55 },
      day: { fontSize: 28 },
      month: { fontSize: 7, marginLeft: 3, marginBottom: 4 },
      copy: { width: 78 },
      weekday: { fontSize: 10 },
      lunar: { fontSize: 6, marginTop: 3 },
      goal: { width: 30, fontSize: 11 },
      metrics: { width: 164, height: 42, marginTop: 3 },
      metric: { width: 38, height: 42, radius: 10, padding: 5 },
      metricLabel: { fontSize: 6 },
      metricValue: { width: 28, fontSize: 10, marginTop: 5 }
    },
    calendar: {
      head: { width: 164, height: 23, marginTop: 3 },
      title: { width: 112, fontSize: 10 },
      nav: { width: 24, height: 22 },
      navText: { fontSize: 16 },
      weekRow: { width: 154, height: 12 },
      week: { width: 22, fontSize: 6 },
      grid: { width: 154, height: 90 },
      cell: { width: 22, height: 15 },
      cellText: { width: 16, height: 13, radius: 7, fontSize: 7 }
    }
  },
  circle: {
    contentWidth: 136,
    surface: 'summary-calendar-pages',
    frame: { left: 28, top: 30, width: 136, height: 128 },
    summary: {
      dateRow: { width: 136, height: 42, radius: 20, paddingY: 5, paddingX: 10 },
      day: { width: 48, height: 34 },
      dayValue: { fontSize: 27 },
      month: { fontSize: 6, marginLeft: 2, marginBottom: 4 },
      dateCopy: { width: 66, marginLeft: 4 },
      weekday: { fontSize: 9 },
      lunar: { fontSize: 5, marginTop: 2 },
      goalRow: { width: 130, height: 12, marginTop: 3 },
      title: { fontSize: 8 },
      goal: { fontSize: 6 },
      goalTrack: { width: 130, height: 3, radius: 2 },
      goalFill: { height: 3, radius: 2 },
      metrics: { width: 130, height: 42, marginTop: 4 },
      metricCard: { width: 63, height: 19, radius: 9, paddingX: 6, marginBottom: 3 },
      metricLabel: { width: 18, fontSize: 6 },
      metricValue: { width: 33, fontSize: 7, lines: 1 },
      action: { width: 74, height: 20, marginTop: 2, radius: 10 },
      actionText: { fontSize: 7 }
    },
    calendar: {
      head: { width: 136, height: 18 },
      title: { width: 92, fontSize: 9 },
      nav: { width: 20, height: 18 },
      navText: { fontSize: 15 },
      weekRow: { width: 133, height: 10 },
      week: { width: 19, fontSize: 5 },
      grid: { width: 133, height: 78 },
      cell: { width: 19, height: 13 },
      cellText: { width: 14, height: 12, radius: 6, fontSize: 6 },
      action: { width: 74, height: 20, marginTop: 2, radius: 10 },
      actionText: { fontSize: 7 }
    }
  },
  pill: {
    contentWidth: 168,
    surface: 'pill-month-calendar',
    frame: { left: 12, top: 52, width: 168, height: 367 },
    summary: {
      dateHero: { width: 168, height: 88, radius: 26, padding: 12 },
      dayBlock: { width: 72, height: 66 },
      monthBadge: { width: 42, height: 20, radius: 10, fontSize: 10, paddingTop: 4 },
      dayValue: { width: 72, height: 48, fontSize: 46 },
      dateCopy: { width: 76, marginLeft: 4 },
      weekday: { fontSize: 16 },
      year: { fontSize: 10, marginTop: 6 },
      lunar: { fontSize: 8, marginTop: 5 },
      summaryRow: { width: 168, height: 24, marginTop: 10 },
      summaryTitle: { fontSize: 15 },
      goal: { fontSize: 9 },
      goalTrack: { width: 168, height: 5, radius: 3 },
      goalFill: { height: 5, radius: 3 },
      grid: { width: 168, height: 144, marginTop: 10 },
      card: { width: 80, height: 68, radius: 18, paddingY: 9, paddingX: 10, marginBottom: 8 },
      label: { fontSize: 8 },
      value: { width: 60, fontSize: 22, marginTop: 3, lines: 1 },
      stepsValue: { fontSize: 18 },
      unit: { fontSize: 7, marginTop: 1 },
      calendarEntry: { width: 168, height: 38, marginTop: 8, radius: 19, paddingX: 14 },
      calendarEntryTitle: { fontSize: 11 },
      calendarEntryIcon: { fontSize: 18 }
    },
    calendar: {
      monthHero: { width: 168, height: 70 },
      monthNumber: { width: 68, fontSize: 46 },
      monthCopy: { width: 100 },
      title: { fontSize: 14 },
      lunar: { fontSize: 8, marginTop: 6 },
      controls: { width: 168, height: 32 },
      button: { width: 80, height: 30, radius: 15 },
      buttonText: { fontSize: 8 },
      weekRow: { width: 154, height: 20, marginTop: 5 },
      week: { width: 22, fontSize: 8 },
      card: { width: 168, height: 180, radius: 24 },
      grid: { width: 154, height: 168 },
      cell: { width: 22, height: 28 },
      cellText: { width: 22, height: 22, radius: 11, fontSize: 9 },
      back: { width: 132, height: 34, marginTop: 9, radius: 17 },
      backText: { fontSize: 9 }
    }
  },
  rect: {
    contentWidth: 164,
    surface: 'calendar-dashboard'
  }
}
