module.exports = {
  base: {
    contentWidth: 164,
    surface: 'summary-record-stream',
    header: { top: 0, width: 164, height: 24 },
    summary: { top: 32, width: 164, height: 46 },
    stream: { top: 86, width: 164 },
    itemHeight: 78,
    itemGap: 7,
    titleSize: 14,
    backSize: 8,
    summaryValueSize: 16,
    summaryLabelSize: 7,
    recordTitleSize: 12,
    recordMetaSize: 7,
    radius: 18,
    padding: 9
  },
  circle: {
    contentWidth: 148,
    header: { absoluteTop: true, top: 24, width: 128, height: 20, circleFit: 'none' },
    summary: { absoluteTop: true, top: 49, width: 140, height: 38, circleFit: 'none' },
    stream: { absoluteTop: true, top: 92, width: 140, height: 90, circleFit: 'none' },
    itemHeight: 66,
    itemGap: 7,
    titleSize: 11,
    backSize: 7,
    summaryValueSize: 13,
    summaryLabelSize: 6,
    recordTitleSize: 10,
    recordMetaSize: 6,
    radius: 14,
    padding: 7
  },
  pill: {
    contentWidth: 168,
    header: { top: 0, width: 168, height: 30 },
    summary: { top: 38, width: 168, height: 58 },
    stream: { top: 104, width: 168 },
    itemHeight: 94,
    itemGap: 10,
    titleSize: 18,
    backSize: 10,
    summaryValueSize: 20,
    summaryLabelSize: 9,
    recordTitleSize: 14,
    recordMetaSize: 9,
    radius: 22,
    padding: 12
  },
  rect: { contentWidth: 164 }
}
