module.exports = {
  base: {
    contentWidth: 164,
    surface: 'rect-dashboard',
    header: { top: 0, width: 164, height: 24 },
    hero: { top: 30, width: 164, height: 64 },
    metrics: { top: 100, width: 164, height: 66 },
    metricColumns: 4,
    metricGap: 4,
    metricHeight: 60,
    actionGap: 8,
    titleSize: 14,
    statusSize: 8,
    durationSize: 31,
    durationLineHeight: 38,
    durationLabelSize: 8,
    gpsSize: 7,
    metricValueSize: 14,
    metricLabelSize: 6,
    actionSize: 11,
    radius: 14
  },
  circle: {
    contentWidth: 148,
    surface: 'circle-focus',
    header: { absoluteTop: true, top: 24, width: 128, height: 18, circleFit: 'none' },
    hero: { absoluteTop: true, top: 45, width: 144, height: 48, circleFit: 'none' },
    metrics: { absoluteTop: true, top: 97, width: 132, height: 54, circleFit: 'none' },
    actions: { absoluteTop: true, top: 153, width: 108, height: 21, circleFit: 'none' },
    metricColumns: 2,
    metricGap: 4,
    metricHeight: 25,
    actionGap: 6,
    titleSize: 10,
    statusSize: 6,
    durationSize: 27,
    durationLineHeight: 31,
    durationLabelSize: 6,
    gpsSize: 5,
    metricValueSize: 11,
    metricLabelSize: 5,
    actionSize: 8,
    radius: 13
  },
  pill: {
    contentWidth: 168,
    surface: 'pill-session',
    header: { top: 0, width: 168, height: 32 },
    hero: { top: 42, width: 168, height: 108 },
    metrics: { top: 164, width: 168, height: 166 },
    actions: { top: 346, width: 168, height: 48 },
    metricColumns: 2,
    metricGap: 8,
    metricHeight: 78,
    actionGap: 10,
    titleSize: 18,
    statusSize: 10,
    durationSize: 50,
    durationLineHeight: 60,
    durationLabelSize: 10,
    gpsSize: 9,
    metricValueSize: 20,
    metricLabelSize: 8,
    actionSize: 15,
    radius: 20
  },
  rect: {
    contentWidth: 164,
    surface: 'rect-dashboard',
    actions: { topFromBottom: 42, width: 164, height: 38 }
  }
}
