const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.resolve(__dirname, '..')
const read = function (name) { return fs.readFileSync(path.join(root, name), 'utf8') }

const healthChannel = read('src/capabilities/internal/health_channel.js')
const heart = read('src/capabilities/heart_rate.js')
const spo2 = read('src/capabilities/blood_oxygen.js')
const stress = read('src/capabilities/stress.js')
const motion = read('src/capabilities/motion.js')
const location = read('src/capabilities/location.js')
const device = read('src/capabilities/device.js')
const battery = read('src/capabilities/battery.js')
const displayPower = read('src/capabilities/display_power.js')
const vibration = read('src/capabilities/vibration.js')
const storage = read('src/capabilities/storage.js')
const powerManager = read('src/common/power_manager.js')
const gpsTracker = read('src/common/gps_tracker.js')
const haptic = read('src/common/haptic_feedback.js')
const profile = read('src/presentation/viewport/profile.js')
const brightnessPage = read('src/pages/settings/brightness/brightness.ux')
const motionPage = read('src/pages/settings/motion/motion.ux')

assert.ok(healthChannel.includes("from '@service.health'"), 'health raw API must be isolated in capability runtime')
assert.ok(healthChannel.includes('listeners.length === 1'), 'health channel must start lazily for first consumer')
assert.ok(healthChannel.includes('listeners.length === 0'), 'health channel must stop after last consumer')
assert.ok(heart.includes("dataTypeName: 'HEART_RATE'"), 'heart rate must be independently triggerable')
assert.ok(spo2.includes("dataTypeName: 'SPO2'"), 'SpO2 must be independently triggerable')
assert.ok(stress.includes("dataTypeName: 'STRESS'"), 'stress must be independently triggerable')

assert.ok(motion.includes("from '@system.sensor'"), 'motion gateway must own accelerometer API')
assert.ok(motion.includes('consumers.length === 0'), 'motion must release native sampling after last consumer')
assert.ok(motion.includes("interval === 'game'"), 'motion gateway must preserve high-rate diagnostics')
assert.ok(motion.includes('desiredInterval()'), 'motion gateway must reconcile consumer sampling needs')
assert.ok(motion.includes('if (active) stopNative()'), 'motion gateway must restart when required sampling cadence changes')
assert.ok(location.includes("from '@system.geolocation'"), 'location gateway must own geolocation API')
assert.ok(location.includes('listeners.length === 1'), 'location must start on first consumer')
assert.ok(location.includes('listeners.length === 0'), 'location must stop after last consumer')

assert.ok(device.includes("from '@system.device'"), 'device gateway must own device API')
assert.ok(battery.includes("from '@system.battery'"), 'battery gateway must own battery API')
assert.ok(displayPower.includes("from '@system.brightness'"), 'display gateway must own brightness API')
assert.ok(displayPower.includes('setMode:'), 'display gateway must own automatic/manual brightness mode')
assert.ok(vibration.includes("from '@system.vibrator'"), 'vibration gateway must own vibrator API')
assert.ok(storage.includes("from '@system.storage'"), 'storage gateway must own storage API')

assert.ok(powerManager.includes("../capabilities/display_power"), 'power manager must use display capability')
assert.ok(powerManager.includes("../capabilities/motion"), 'power manager must use motion capability')
assert.ok(!powerManager.includes('@system.'), 'power manager must never regress to raw system APIs')
assert.ok(gpsTracker.includes("../capabilities/location"), 'GPS tracker must use location capability')
assert.ok(!gpsTracker.includes('@system.geolocation'), 'GPS tracker must not own geolocation API')
assert.ok(haptic.includes("../capabilities/vibration"), 'haptic logic must use vibration capability')
assert.ok(!haptic.includes('@system.vibrator'), 'haptic logic must not own vibrator API')
assert.ok(profile.includes("../../capabilities/device"), 'viewport must consume device capability')
assert.ok(!profile.includes('platform/vela'), 'viewport must not use retired platform layer')

assert.ok(brightnessPage.includes("../../../capabilities/display_power"), 'brightness settings must use display capability')
assert.ok(!brightnessPage.includes("from '@system.brightness'"), 'brightness settings must not access the raw brightness API')
assert.ok(motionPage.includes("../../../capabilities/motion"), 'motion diagnostics must use motion capability')
assert.ok(motionPage.includes("interval: 'game'"), 'motion diagnostics must request its sampling intent through the gateway')
assert.ok(!motionPage.includes("from '@system.sensor'"), 'motion diagnostics must not access the raw sensor API')

console.log('Capability Runtime verified: device APIs are isolated, lazy and independently triggerable')
