const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.resolve(__dirname, '..')
const read = function (name) { return fs.readFileSync(path.join(root, name), 'utf8') }

const detail = read('src/pages/detail/detail.ux')
const settings = read('src/pages/settings/settings/settings.ux')
const workout = read('src/pages/workout/workout.ux')
const workoutSelect = read('src/pages/workout_select/workout_select.ux')
const history = read('src/pages/history/history.ux')
const applist = read('src/pages/applist/applist.ux')
const watchface = read('src/pages/watchface/index.ux')
const detailSpec = read('src/presentation/layout/specs/detail.js')
const settingsSpec = read('src/presentation/layout/specs/settings.js')
const workoutSpec = read('src/presentation/layout/specs/workout.js')
const workoutSelectSpec = read('src/presentation/layout/specs/workout_select.js')
const historySpec = read('src/presentation/layout/specs/history.js')
const applistSpec = read('src/presentation/layout/specs/applist.js')
const watchfaceSpec = read('src/presentation/layout/specs/watchface_selector.js')
const pagedStack = read('src/presentation/layout/paged_stack.js')
const scrollFlow = read('src/presentation/layout/scroll_flow.js')
const freeSurface = read('src/presentation/layout/free_surface.js')
const appCatalog = read('src/domain/apps/catalog.js')
const watchfaceCatalog = read('src/domain/watchface/catalog.js')
const honeycombEngine = read('src/presentation/engines/honeycomb.js')

assert.ok(detail.includes("../../presentation/layout/runtime"), 'L1 detail must enter through Design Engine runtime')
assert.ok(detail.includes("../../presentation/layout/specs/detail"), 'L1 detail must keep layout intent outside the page')
assert.ok(!detail.includes('@media (shape:'), 'L1 detail must not regain shape-specific CSS')
assert.ok(detailSpec.includes('freedomLevel: 1'), 'detail spec must declare L1')

assert.ok(settings.includes("../../../presentation/layout/runtime"), 'L1 settings must enter through Design Engine runtime')
assert.ok(settings.includes("../../../presentation/layout/paged_stack"), 'L1 settings must use automatic paged capacity')
assert.ok(settings.includes("../../../presentation/layout/specs/settings"), 'L1 settings layout intent must live in a spec')
assert.ok(settings.includes('pagedStack.resolvePage'), 'partial settings pages must reflow actual visible items without changing capacity')
assert.ok(settings.includes('$item.marginBottom'), 'L1 card rhythm must represent real between-item gaps rather than space-between holes')
assert.ok(!settings.includes('profile.isCircle'), 'L1 settings must not hardcode circle page capacity')
assert.ok(!settings.includes('justify-content: space-between;\n}\n\n.settings-item'), 'settings list must not spread partial pages across reserved capacity')
assert.ok(!settings.includes('@media (shape:'), 'L1 settings must not regain shape-specific geometry CSS')
assert.ok(settingsSpec.includes('freedomLevel: 1'), 'settings spec must declare L1')
assert.ok(pagedStack.includes('for (var count = maxItems; count >= minItems; count--)'), 'paged stack must derive the largest safe page capacity')
assert.ok(pagedStack.includes('expandComfort'), 'paged stack must use spare tall-screen space instead of freezing at circle density')
assert.ok(pagedStack.includes('function resolvePage'), 'paged stack must separate navigation capacity from actual visible-page geometry')
assert.ok(pagedStack.includes('visualScale'), 'paged stack must expose presentation comfort scale separately from geometry scale')
assert.ok(pagedStack.includes('capacityReduced'), 'paged stack must expose automatic capacity decisions')

assert.ok(workoutSelect.includes("../../presentation/layout/scroll_flow"), 'L1 workout selector must use scroll-flow primitive')
assert.ok(workoutSelect.includes("../../presentation/layout/specs/workout_select"), 'L1 workout selector intent must live in a spec')
assert.ok(!workoutSelect.includes('@media (shape:'), 'L1 workout selector must not regain shape-specific CSS')
assert.ok(!workoutSelect.includes('pageViewport.bind'), 'L1 workout selector must enter through Design Engine runtime')
assert.ok(workoutSelectSpec.includes('freedomLevel: 1'), 'workout selector spec must declare L1')
assert.ok(workoutSelectSpec.includes("regionId: 'stream'"), 'workout selector must reserve a real scrolling viewport')
assert.ok(workoutSelectSpec.includes('growViewport: true'), 'tall screens should automatically expand the mode stream')

assert.ok(workout.includes("../../presentation/layout/runtime"), 'L2 workout must use Design Engine runtime')
assert.ok(workout.includes("../../presentation/layout/specs/workout"), 'L2 workout must keep composition in a layout spec')
assert.ok(workoutSpec.includes('freedomLevel: 2'), 'workout spec must declare L2')
assert.ok(workoutSpec.includes("strategy: 'assisted'"), 'workout must remain an assisted design')
assert.ok(workoutSpec.includes('fixed-composition'), 'L2 workout may art-direct a shape-specific composition')

assert.ok(history.includes("../../presentation/layout/scroll_flow"), 'L2 history must distinguish composed viewport content from scrolling flow')
assert.ok(history.includes("../../presentation/layout/specs/history"), 'history art direction must live outside the page')
assert.ok(!history.includes('@media (shape:'), 'history top-level geometry must come from composition rather than shape CSS')
assert.ok(historySpec.includes('freedomLevel: 2'), 'history spec must declare L2')
assert.ok(historySpec.includes("insightVariant: 'column'"), 'rect history may use a distinct dashboard composition')
assert.ok(scrollFlow.includes("flowMode = 'composed-header-scroll'"), 'scroll flow must explicitly separate fixed composition from stream semantics')
assert.ok(scrollFlow.includes('heroHeight'), 'scroll flow must expose normal-flow handoff after composed header')

assert.ok(applist.includes("../../presentation/layout/free_surface"), 'L3 launcher must resolve its art-directed surface through Design Engine')
assert.ok(applist.includes("../../domain/apps/catalog"), 'L3 surfaces must share one domain app catalog')
assert.ok(applist.includes("../../presentation/engines/honeycomb"), 'circle launcher must consume its visual engine directly')
assert.ok(applist.includes("surface === 'designed-grid'"), 'rect must render a dedicated designed grid')
assert.ok(applist.includes("surface === 'paged-list'"), 'pill must retain a dedicated list composition')
assert.ok(applistSpec.includes('freedomLevel: 3'), 'launcher spec must declare L3 free design')
assert.ok(applistSpec.includes("surface: 'honeycomb'"), 'circle launcher must retain a honeycomb surface')
assert.ok(applistSpec.includes("surface: 'paged-list'"), 'pill launcher must retain a paged-list surface')
assert.ok(applistSpec.includes("surface: 'designed-grid'"), 'rect launcher must own a designed grid surface')
assert.ok(freeSurface.includes('plan.surface = selected.surface'), 'L3 resolver must expose selected surface without auto-recomposing it')
assert.ok(freeSurface.includes('plan.itemIds = itemIds.slice()'), 'free surface must support generic semantic item catalogs')
assert.ok(!appCatalog.includes('PILL_APP_IDS') && !appCatalog.includes('CIRCLE_APP_IDS'), 'domain app catalog must stay shape-agnostic')
assert.ok(honeycombEngine.includes('SPACING = 46'), 'honeycomb visual math belongs in presentation engine')

assert.ok(watchface.includes("../../domain/watchface/store"), 'watchface selector must persist through the watchface domain directly')
assert.ok(watchface.includes("../../domain/watchface/catalog"), 'watchface selector must share one shape-agnostic face catalog')
assert.ok(watchface.includes("../../presentation/layout/specs/watchface_selector"), 'watchface selector art direction must live in an L3 spec')
assert.ok(watchface.includes("surface === 'cards-pager'"), 'pill watchface selector must own cards/pager surface')
assert.ok(watchface.includes("surface === 'preview-swiper'"), 'circle watchface selector must own preview swiper surface')
assert.ok(watchface.includes("surface === 'preview-grid'"), 'rect watchface selector must own preview grid surface')
assert.ok(!watchface.includes('watchData'), 'watchface selector must not regress to watch_data compatibility storage')
assert.ok(!watchface.includes('profile.isCircle') && !watchface.includes('profile.isPill'), 'L3 page must consume surface decisions rather than hardcode shape logic')
assert.ok(watchfaceSpec.includes('freedomLevel: 3'), 'watchface selector spec must declare L3')
assert.ok(watchfaceSpec.includes("surface: 'preview-swiper'"), 'circle watchface selector design must remain explicit')
assert.ok(watchfaceSpec.includes("surface: 'cards-pager'"), 'pill watchface selector design must remain explicit')
assert.ok(watchfaceSpec.includes("surface: 'preview-grid'"), 'rect watchface selector design must remain explicit')
assert.ok(!watchfaceCatalog.includes('circleOnly') && !watchfaceCatalog.includes('pillOnly'), 'domain watchface catalog must not own shape exposure policy')

console.log('Design freedom boundary verified: L1 automates repetition, L2 assists composition, L3 preserves independent surfaces')
