const fs = require('fs')
const path = require('path')
const assert = require('assert')

const root = path.resolve(__dirname, '..')
const read = function (name) { return fs.readFileSync(path.join(root, name), 'utf8') }

const detail = read('src/pages/detail/detail.ux')
const settings = read('src/pages/settings/settings/settings.ux')
const workout = read('src/pages/workout/workout.ux')
const history = read('src/pages/history/history.ux')
const detailSpec = read('src/presentation/layout/specs/detail.js')
const settingsSpec = read('src/presentation/layout/specs/settings.js')
const workoutSpec = read('src/presentation/layout/specs/workout.js')
const historySpec = read('src/presentation/layout/specs/history.js')
const applistSpec = read('src/presentation/layout/specs/applist.js')
const pagedStack = read('src/presentation/layout/paged_stack.js')
const scrollFlow = read('src/presentation/layout/scroll_flow.js')
const freeSurface = read('src/presentation/layout/free_surface.js')
const appCatalog = read('src/domain/apps/catalog.js')
const honeycombEngine = read('src/presentation/engines/honeycomb.js')

assert.ok(detail.includes("../../presentation/layout/runtime"), 'L1 detail must enter through Design Engine runtime')
assert.ok(detail.includes("../../presentation/layout/specs/detail"), 'L1 detail must keep layout intent outside the page')
assert.ok(!detail.includes('@media (shape:'), 'L1 detail must not regain shape-specific CSS')
assert.ok(detailSpec.includes('freedomLevel: 1'), 'detail spec must declare L1')

assert.ok(settings.includes("../../../presentation/layout/runtime"), 'L1 settings must enter through Design Engine runtime')
assert.ok(settings.includes("../../../presentation/layout/paged_stack"), 'L1 settings must use automatic paged capacity')
assert.ok(settings.includes("../../../presentation/layout/specs/settings"), 'L1 settings layout intent must live in a spec')
assert.ok(!settings.includes('profile.isCircle'), 'L1 settings must not hardcode circle page capacity')
assert.ok(!settings.includes('@media (shape:'), 'L1 settings must not regain shape-specific geometry CSS')
assert.ok(settingsSpec.includes('freedomLevel: 1'), 'settings spec must declare L1')
assert.ok(pagedStack.includes('for (var count = maxItems; count >= minItems; count--)'), 'paged stack must derive the largest safe page capacity')
assert.ok(pagedStack.includes('expandComfort'), 'paged stack must use spare tall-screen space instead of freezing at circle density')
assert.ok(pagedStack.includes('visualScale'), 'paged stack must expose presentation comfort scale separately from geometry scale')
assert.ok(pagedStack.includes('capacityReduced'), 'paged stack must expose automatic capacity decisions')

assert.ok(workout.includes("../../presentation/layout/runtime"), 'L2 workout must use Design Engine runtime')
assert.ok(workout.includes("../../presentation/layout/specs/workout"), 'L2 workout must keep composition in a layout spec')
assert.ok(workoutSpec.includes('freedomLevel: 2'), 'workout spec must declare L2')
assert.ok(workoutSpec.includes("strategy: 'assisted'"), 'workout must remain an assisted design')
assert.ok(workoutSpec.includes('fixed-composition'), 'L2 workout may art-direct a shape-specific composition')

assert.ok(history.includes("../../presentation/layout/scroll_flow"), 'L2 history must distinguish composed viewport content from scrolling flow')
assert.ok(history.includes("../../presentation/layout/specs/history"), 'history art direction must live outside the page')
assert.ok(!history.includes('@media (shape:'), 'history top-level geometry must come from composition rather than shape CSS')
assert.ok(historySpec.includes('freedomLevel: 2'), 'history spec must declare L2')
assert.ok(historySpec.includes("insightVariant: 'column'"), 'rect history may use a distinct dashboard composition')
assert.ok(scrollFlow.includes("flowMode = 'composed-header-scroll'"), 'scroll flow must explicitly separate fixed composition from stream semantics')
assert.ok(scrollFlow.includes('heroHeight'), 'scroll flow must expose normal-flow handoff after composed header')

assert.ok(applistSpec.includes('freedomLevel: 3'), 'launcher spec must declare L3 free design')
assert.ok(applistSpec.includes("surface: 'honeycomb'"), 'circle launcher must retain a honeycomb surface')
assert.ok(applistSpec.includes("surface: 'paged-list'"), 'pill launcher must retain a paged-list surface')
assert.ok(applistSpec.includes("surface: 'designed-grid'"), 'rect launcher must own a designed grid surface')
assert.ok(freeSurface.includes('plan.surface = selected.surface'), 'L3 resolver must expose selected surface without auto-recomposing it')
assert.ok(freeSurface.includes('plan.appIds = selected.appIds'), 'L3 surface may choose exposure while reusing shared app semantics')
assert.ok(!appCatalog.includes('PILL_APP_IDS') && !appCatalog.includes('CIRCLE_APP_IDS'), 'domain app catalog must stay shape-agnostic')
assert.ok(honeycombEngine.includes('SPACING = 46'), 'honeycomb visual math belongs in presentation engine')

console.log('Design freedom boundary verified: L1 automates repetition, L2 assists composition, L3 preserves independent surfaces')
