const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = name => fs.readFileSync(path.join(root, name), 'utf8')
const exists = name => fs.existsSync(path.join(root, name))

const repository = read('src/domain/history/repository.js')
const controller = read('src/v2/features/history/controller.js')
const view = read('src/v2/design/apps/history/view.js')

assert.strictEqual(exists('src/domain/health/recent.js'), false, 'History must not regain seeded health state')
assert.ok(repository.includes("HISTORY_KEY = 'activity_history_v3'"), 'History must use the clean V3 persistence namespace')
assert.ok(!repository.includes('makeDemoHistory'), 'History must not fabricate missing activity history')
assert.ok(!repository.includes('makeDemoHourly'), 'History must not fabricate hourly heart-rate history')
assert.ok(!repository.includes('hourlyHeartRate'), 'Retired demo hourly heart-rate state must stay removed')
assert.ok(!repository.includes("../health/recent"), 'History must not depend on seeded compatibility health data')
assert.ok(!repository.includes("'health_history_7d'"), 'V3 must not reopen the persistence namespace that may contain seeded legacy history')
assert.ok(!repository.includes("../activity/store"), 'History Repository must not act as a second Activity persistence owner')
assert.ok(!repository.includes('restoreTotals'), 'Reading History must never restore or repair current Activity totals')
assert.ok(!repository.includes('ensure:'), 'History must not retain a read-and-rewrite compatibility initializer')
assert.ok(repository.includes('History saveToday requires canonical Activity snapshot'), 'History writes must require an explicit canonical Activity snapshot')
assert.ok(repository.includes('V3 history persistence must be an array'), 'Malformed V3 history containers must fail visibly')
assert.ok(repository.includes('Invalid V3 history field:'), 'Malformed V3 history fields must fail visibly')
assert.ok(!repository.includes('finiteNumber') && !repository.includes('Number(record.'), 'History persistence must not coerce malformed record fields')
assert.ok(!/Math\.(?:min|max)\s*\(/.test(repository), 'History persistence must not clamp malformed record fields')
assert.ok(repository.includes('avgHeartRate: null'), 'History Repository must preserve unavailable heart rate as null')
assert.ok(controller.includes('heartCount ? Math.round(totalHeart / heartCount) : null'), 'History Feature must preserve unavailable aggregate heart rate as null')
assert.ok(view.includes("model.avgHeartRate === null ? '--' : model.avgHeartRate + ' bpm'"), 'History View must convert null to display text only at presentation time')
assert.ok(!controller.includes('Number(item.steps)') && !controller.includes('Number(item.avgHeartRate)'), 'History Feature must trust Repository records')
assert.ok(!controller.includes('summarize: summarize'), 'History Feature must not expose its internal reducer as product API')

console.log('History truth contracts verified: strict V3 persistence, one owner, no seeded data and no null-to-zero fallback chain')
