const fs = require('fs')
const path = require('path')
const assert = require('assert')
const powerState = require('../src/domain/power/state_machine')
const powerPolicy = require('../src/domain/power/policy')

const root = path.resolve(__dirname, '..')
const runtimeSource = fs.readFileSync(path.join(root, 'src/runtime/power/controller.js'), 'utf8')

assert.strictEqual(powerState.modeForIdle(0), powerState.MODE_ACTIVE)
assert.strictEqual(powerState.modeForIdle(7999), powerState.MODE_ACTIVE)
assert.strictEqual(powerState.modeForIdle(8000), powerState.MODE_DIM)
assert.strictEqual(powerState.modeForIdle(14999), powerState.MODE_DIM)
assert.strictEqual(powerState.modeForIdle(15000), powerState.MODE_SLEEP)

const machine = powerState.create(1000)
assert.strictEqual(machine.getSnapshot().mode, powerState.MODE_ACTIVE)
assert.strictEqual(machine.evaluate(8999).mode, powerState.MODE_ACTIVE)
assert.strictEqual(machine.evaluate(9000).mode, powerState.MODE_DIM)
assert.strictEqual(machine.evaluate(16000).mode, powerState.MODE_SLEEP)
assert.strictEqual(machine.markActive('touch', 17000).mode, powerState.MODE_ACTIVE)
assert.strictEqual(machine.getSnapshot().lastActiveAt, 17000)

const active = powerPolicy.get(powerState.MODE_ACTIVE)
const dim = powerPolicy.get(powerState.MODE_DIM)
const sleep = powerPolicy.get(powerState.MODE_SLEEP)

assert.strictEqual(active.timeInterval, 1000, 'ACTIVE clock refresh must stay 1s')
assert.strictEqual(active.heartInterval, 3000, 'ACTIVE heart cadence must stay 3s')
assert.strictEqual(active.healthEnabled, true, 'ACTIVE keeps health sampling on')

assert.strictEqual(dim.timeInterval, 5000, 'DIM clock refresh must stay 5s')
assert.strictEqual(dim.heartInterval, 30000, 'DIM business heart updates must stay 30s')
assert.strictEqual(dim.healthEnabled, true, 'DIM keeps the health subscription alive')

assert.strictEqual(sleep.heartInterval, 0, 'SLEEP must stop heart business updates')
assert.strictEqual(sleep.batteryInterval, 0, 'SLEEP must stop battery polling')
assert.strictEqual(sleep.healthEnabled, false, 'SLEEP must release health sampling')
assert.strictEqual(sleep.keepScreenOn, false, 'SLEEP must let the screen turn off')

assert.ok(runtimeSource.includes("../../capabilities/heart_rate"), 'power runtime must own watchface HR capability lifecycle')
assert.ok(runtimeSource.includes("../../capabilities/battery"), 'power runtime must own watchface battery reads')
assert.ok(runtimeSource.includes("../../capabilities/motion"), 'power runtime must own raise-wake motion lifecycle')
assert.ok(runtimeSource.includes("../../capabilities/display_power"), 'power runtime must own display power effects')
assert.ok(runtimeSource.includes("currentMode === stateMachine.MODE_ACTIVE) onHeartRate(sample, 'live')"), 'ACTIVE must publish live HR immediately')
assert.ok(runtimeSource.includes("onHeartRate(latestHeartSample, 'cadence')"), 'DIM/ACTIVE cadence timer must publish buffered HR')
assert.ok(runtimeSource.includes('if (policy.healthEnabled) startHealth()'), 'health subscription must follow power policy')
assert.ok(runtimeSource.includes('else stopHealth()'), 'SLEEP must release health capability')
assert.ok(runtimeSource.includes("motion.subscribe(handleRaiseWake, { interval: 'normal' })"), 'raise-wake must use low-cost normal motion cadence')
assert.ok(!runtimeSource.includes('@system.'), 'power runtime must never own raw Vela APIs')
assert.ok(!runtimeSource.includes('@service.'), 'power runtime must never own raw Vela services')

console.log('Power runtime verified: ACTIVE/DIM/SLEEP, buffered HR, battery and raise-wake cadence are preserved')
