const assert = require('assert')
const fs = require('fs')
const path = require('path')
const readResult = require('../src/capabilities/internal/storage_read_result')

let classified = readResult.json('settings', '{"ok":true}', null)
assert.deepStrictEqual(classified.value, { ok: true })
assert.strictEqual(classified.result.ok, true)
assert.strictEqual(classified.result.status, 'ok')

classified = readResult.json('settings', '', { fallback: true })
assert.deepStrictEqual(classified.value, { fallback: true })
assert.strictEqual(classified.result.ok, true)
assert.strictEqual(classified.result.status, 'missing')

classified = readResult.json('settings', '{broken json', { fallback: true })
assert.deepStrictEqual(classified.value, { fallback: true }, 'corrupt JSON may expose an in-memory fallback but must retain an explicit corrupt result')
assert.strictEqual(classified.result.ok, false)
assert.strictEqual(classified.result.status, 'corrupt')
assert.ok(classified.result.error instanceof Error)
assert.ok(/Invalid persisted JSON for settings/.test(classified.result.error.message))

const ioError = new Error('native read failed')
classified = readResult.io({ fallback: true }, ioError)
assert.deepStrictEqual(classified.value, { fallback: true })
assert.strictEqual(classified.result.ok, false)
assert.strictEqual(classified.result.status, 'io-error')
assert.strictEqual(classified.result.error, ioError)

const rawMissing = readResult.raw(undefined, '')
assert.strictEqual(rawMissing.value, '')
assert.strictEqual(rawMissing.result.status, 'missing')
const rawValue = readResult.raw('mechanical', '')
assert.strictEqual(rawValue.value, 'mechanical')
assert.strictEqual(rawValue.result.status, 'ok')

const root = path.resolve(__dirname, '..')
const storage = fs.readFileSync(path.join(root, 'src/capabilities/storage.js'), 'utf8')
assert.ok(storage.includes('getJSONResult: function'), 'Storage must expose structured JSON reads for recoverable user-data errors')
assert.ok(storage.includes('getResult: function'), 'Storage must expose structured raw reads for recoverable user-data errors')
assert.ok(storage.includes('quarantine: function'), 'Storage must expose explicit quarantine instead of silently overwriting corrupt content')
const backupIndex = storage.indexOf('adapter.set(backupKey, envelope')
const deleteIndex = storage.indexOf('adapter.delete(key')
assert.ok(backupIndex >= 0 && deleteIndex > backupIndex, 'quarantine must persist the raw backup before deleting the original key')
assert.ok(storage.includes("status: 'quarantined'"), 'successful quarantine must be observable')
assert.ok(storage.includes("status: 'io-error'"), 'quarantine I/O failure must be observable')

console.log('Storage recovery core verified: missing/corrupt/I-O reads are structured and quarantine preserves raw content before deletion')
