const assert = require('assert')
const fs = require('fs')
const path = require('path')
const freeSurface = require('../src/presentation/layout/free_surface')
const todayLayout = require('../src/presentation/layout/specs/today')
const safeArea = require('../src/common/safe_area')

const root = path.resolve(__dirname, '..')
const page = fs.readFileSync(path.join(root, 'src/pages/today/today.ux'), 'utf8')

function profile(shape, height) {
  return { formFactor: shape, logicalHeight: height }
}

const circle = freeSurface.resolve(profile('circle', 192), todayLayout)
const pill = freeSurface.resolve(profile('pill', 490), todayLayout)
const rect = freeSurface.resolve(profile('rect', 228), todayLayout)

assert.strictEqual(circle.freedomLevel, 2)
assert.strictEqual(circle.strategy, 'assisted')
assert.strictEqual(circle.surface, 'circle-dual-page')
assert.strictEqual(circle.pageSize, 2)
assert.strictEqual(circle.tokens.calendar, true)
assert.strictEqual(safeArea.fitsInCircle(192, 28, 31, 136, 130), true, 'circle Today surface must remain inside the shared safe band')

assert.strictEqual(pill.surface, 'pill-month-gallery')
assert.strictEqual(pill.pageSize, 2)
assert.strictEqual(pill.tokens.calendarVariant, 'gallery')
assert.ok(page.includes('<stack class="today-page'), 'Today must use a non-scrolling layered root container')
assert.ok(!page.includes('<stack class="today-page {{ viewportClass }}" style="position: {{ viewportPosition }}; left: {{ viewportLeft }}; top: {{ viewportTop }}; width: {{ viewportWidth }}; height: {{ viewportHeight }}; opacity: {{ pageOpacity }}; margin-left: {{ pageOffset }}px;" @swipe='), 'pill must not inherit a root swipe recognizer')
assert.ok(page.includes('.pill-month-number'), 'pill must own a large month-number visual language')
assert.ok(page.includes('.pill-calendar-card'), 'pill must own a dedicated full month card')
assert.ok(page.includes('.pill-week-row { width: 154px;'), 'pill weekday row must use the shared seven-column grid width')
assert.ok(page.includes('.pill-week { width: 22px;'), 'pill weekday labels must match calendar column width')
assert.ok(page.includes('.pill-calendar-grid { width: 154px;'), 'pill dates must use the same seven-column grid width')
assert.ok(page.includes('.pill-calendar-cell { width: 22px;'), 'pill dates must align one-to-one with weekday columns')
assert.ok(page.includes('width: 168px; height: 198px'), 'pill month card should deliberately use tall-screen space without overflowing')
assert.ok(!page.includes('border-bottom-width: 1px'), 'pill month hero must not render the accidental framed divider')
assert.ok(page.includes('pill-summary-surface" if="{{ profileReady && isPillSurface && surfacePageIndex === 0 }}" @swipe="handlePillSwipe"'), 'pill summary must own a native non-bubbling swipe recognizer')
assert.ok(page.includes('pill-calendar-surface" if="{{ profileReady && isPillSurface && surfacePageIndex === 1 }}" @swipe="handlePillSwipe"'), 'pill calendar must own a native non-bubbling swipe recognizer')
assert.ok(page.includes('handlePillSwipe(event)'), 'pill surface must resolve Vela swipe direction directly')
assert.ok(page.includes("event.direction === 'up'"), 'pill native swipe must support next-month navigation')
assert.ok(page.includes("event.direction === 'down'"), 'pill native swipe must support previous-month navigation')
assert.ok(!page.includes('@touchstart=') && !page.includes('@touchmove=') && !page.includes('@touchend='), 'Today must not regress to raw touch gesture recognition')
assert.ok(!page.includes('pillTouchStartX') && !page.includes('pillTouchStartY') && !page.includes('pillTouchTracking'), 'Today must not retain raw touch tracking state')
assert.ok(!page.includes('preventDefault') && !page.includes('stopPropagation'), 'Vela gesture handling must not depend on DOM cancellation semantics')
assert.ok(page.includes('pillStepsFontSize'), 'pill summary must adapt typography for long step values')
assert.ok(page.includes('metricFontSize(view.stepsText)'), 'step typography must respond to formatted value length')
assert.ok(page.includes('.pill-steps-value { width: 58px;'), 'pill step value must use the full metric-card content width')
assert.ok(!page.includes('pill-summary-hint'), 'pill summary must not keep an invisible bottom hint that extends the surface')
assert.ok(!page.includes('pill-surface-pager'), 'pill pages must not keep invisible bottom pager decoration')
assert.ok(!page.includes('pill-calendar-footer'), 'pill calendar must not keep an off-screen footer')
assert.ok(page.includes('rect-dashboard-surface" if="{{ profileReady && isRectSurface }}" @swipe="handleSwipe"'), 'rect surface should own its swipe handler directly')
assert.ok(page.includes('circle-summary-surface" if="{{ profileReady && isCircleSurface && surfacePageIndex === 0 }}" @swipe="handleSwipe"'), 'circle surface should own its swipe handler directly')

assert.strictEqual(rect.surface, 'rect-calendar-dashboard')
assert.strictEqual(rect.pageSize, 1)
assert.strictEqual(rect.tokens.calendarVariant, 'dashboard')
assert.ok(page.includes('.rect-metric-strip'), 'rect Today should use a horizontal metric dashboard')
assert.ok(page.includes('.rect-calendar-grid'), 'rect Today must retain calendar capability')

assert.ok(page.includes("../../common/calendar_utils"), 'all surfaces must reuse one calendar engine')
assert.ok(page.includes("../../domain/activity/store"), 'all surfaces must reuse one activity state source')
assert.ok(page.includes("../../domain/health/store"), 'all surfaces must reuse one health state source')
assert.ok(page.includes('calendarUtils.buildMonth'), 'month building must remain shared functionality')
assert.ok(page.includes('calendarUtils.shiftMonth'), 'month navigation must remain shared functionality')
assert.ok(!page.includes('profile.isCircle') && !page.includes('profile.isPill'), 'Today must consume surfaces rather than shape branching')
assert.ok(!page.includes('@media (shape:'), 'Today top-level design must not regress to shape CSS')

console.log('Today L2 verified: pill uses native non-bubbling swipe without raw touch tracking or scroll semantics')
