const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = name => fs.readFileSync(path.join(root, name), 'utf8')

const clock = read('src/v2/features/clock/controller.js')
const health = read('src/v2/features/health/controller.js')
const workout = read('src/v2/features/workout/controller.js')
const normalizedWorkout = workout.replace(/\r\n/g, '\n')
const notification = read('src/v2/features/notification/controller.js')
const sync = read('src/v2/features/sync/controller.js')
const syncTransport = read('src/v2/features/sync/mock_transport.js')
const settingsStore = read('src/domain/settings/store.js')
const settingsStoreCore = read('src/domain/settings/store_core.js')
const eventGateway = read('src/capabilities/system_event.js')
const interconnectGateway = read('src/capabilities/interconnect.js')
const motionController = read('src/v2/features/settings/motion_controller.js')
const vibrationController = read('src/v2/features/settings/vibration_controller.js')
const haptics = read('src/v2/system/haptics.js')
const hapticsCore = read('src/v2/system/haptics_core.js')

assert.ok(clock.includes('powerRuntime.start()'), 'Clock start must activate the power runtime')
assert.ok(clock.includes('powerRuntime.stop()'), 'Clock stop must release the power runtime')
assert.ok(clock.includes('notification.start()') && clock.includes('notification.stop()'), 'Clock lifecycle must own its notification consumer')
assert.ok(clock.includes("historyRepository.saveToday(activityStore.getSnapshot()"), 'Clock lifecycle must persist semantic daily state without page-owned storage')

assert.ok(health.includes('lifecycleGeneration'), 'Health async callbacks must belong to one visible lifecycle generation')
assert.ok(health.includes('if (!started || generation !== lifecycleGeneration) return'), 'stale Health callbacks must not update a stopped page')
assert.ok(health.includes('healthStore.subscribeAll(onHealth)') && health.includes('healthStore.unsubscribe(onHealth)'), 'Health lifecycle must own exactly one health subscription')

assert.ok(workout.includes('location.subscribe('), 'running workout must activate location only through the capability gateway')
assert.ok(workout.includes('location.unsubscribe('), 'workout pause/stop must release location')
assert.ok(workout.includes("import heartRate from '../../../capabilities/heart_rate'"), 'Workout heart rate must come through the official heart-rate capability')
assert.ok(workout.includes('heartRate.subscribe(onHeartRate)'), 'running workout must subscribe to official heart rate')
assert.ok(workout.includes('heartRate.unsubscribe(onHeartRate)'), 'workout pause/stop must release the heart-rate consumer')
assert.ok(workout.includes("snapshot.source !== 'live'"), 'Workout must reject compatibility fallback heart-rate samples')
assert.ok(workout.includes('setInterval('), 'running workout may own one session tick')
assert.ok(workout.includes('clearInterval('), 'workout lifecycle must release the session tick')
assert.ok(workout.includes('lifecycleGeneration'), 'workout async restore/start callbacks must be lifecycle scoped')
assert.ok(workout.includes('if (!isCurrent(generation)) return'), 'stale workout callbacks must not restart a stopped runtime')
assert.ok(workout.includes("if (!active || active.status !== 'running') return"), 'location and health resources must not run without one active running session')
assert.ok(normalizedWorkout.includes('stopTimer()\n      stopLocation()\n      stopHeartRate()\n      persist()'), 'paused workout must release its 1Hz tick, location and heart-rate resources')
assert.ok(workout.includes('stopRuntime(false)'), 'finish/cancel must not write an active snapshot immediately before clearing it')
assert.ok(workout.includes('activityStore.addAndPersist('), 'workout finish must commit activity in feature orchestration')
assert.ok(workout.includes('historyRepository.saveToday('), 'workout finish must update seven-day history in feature orchestration')
assert.ok(workout.includes('workoutRepository.saveRecord('), 'workout finish must persist the workout record in feature orchestration')

assert.ok(notification.includes('systemEvent.subscribe(EVENT_NAME, onExternal)'), 'notification runtime must lazily subscribe to external events')
assert.ok(notification.includes('systemEvent.unsubscribe(EVENT_NAME, onExternal)'), 'notification runtime must release event subscription')
assert.ok(notification.includes('interconnect.subscribe(onExternal)'), 'notification runtime must lazily subscribe to interconnect')
assert.ok(notification.includes('interconnect.unsubscribe(onExternal)'), 'notification runtime must release interconnect')
assert.ok(notification.includes("HAPTIC_OWNER = 'notification'"), 'notification haptics must have an explicit lifecycle owner')
assert.ok(notification.includes('haptics.stop(HAPTIC_OWNER)'), 'notification dismiss must only stop its own haptic run')
assert.ok(eventGateway.includes('subscriptions.length'), 'system-event gateway must track active consumers')
assert.ok(interconnectGateway.includes('if (listeners.length === 0) disconnect()'), 'interconnect must disconnect after its final consumer')

assert.ok(motionController.includes('motion.subscribe('), 'motion diagnostics must consume the motion gateway')
assert.ok(motionController.includes('motion.unsubscribe('), 'motion diagnostics must release the motion gateway')
assert.ok(!motionController.includes('@system.sensor'), 'motion feature must never bypass its capability gateway')
assert.ok(motionController.includes("HAPTIC_OWNER = 'motion-diagnostics'"), 'motion haptics must have an explicit lifecycle owner')
assert.ok(motionController.includes('cancelMeasure()'), 'motion lifecycle must cancel one measurement generation before reset/stop')
assert.ok(motionController.includes('haptics.stop(HAPTIC_OWNER)'), 'motion stop must not cancel another Feature haptic run')

assert.ok(vibrationController.includes("HAPTIC_OWNER = 'settings-vibration'"), 'vibration settings must have an explicit haptic lifecycle owner')
assert.ok(vibrationController.includes('haptics.stop(HAPTIC_OWNER)'), 'vibration settings must only stop its own feedback')
assert.ok(vibrationController.includes("haptics.play(normalized, state.vibrationLevel, HAPTIC_OWNER) ? 'played' : 'unavailable'"), 'vibration feedback status must use the real execution result')

assert.ok(haptics.includes("require('./haptics_core')"), 'system haptics must delegate arbitration to its executable core')
assert.ok(hapticsCore.includes('activeOwner'), 'haptics runtime must track one physical executor owner')
assert.ok(hapticsCore.includes('generation !== expectedRun'), 'stale delayed pulses must be generation guarded')
assert.ok(hapticsCore.includes('activeOwner !== owner'), 'a stale consumer must not stop the current owner')

assert.ok(sync.includes('if (active) return emit()'), 'repeated onShow/load must not reset an active sync lifecycle')
assert.ok(sync.includes('lifecycleEpoch++') && sync.includes('isLive(epoch)'), 'sync callbacks must be scoped to a visible lifecycle generation')
assert.ok(sync.includes('if (!isLive(epoch) || !state.syncing) return'), 'stale sync collection/send callbacks must not revive a stopped transaction')
assert.ok(sync.includes('transportFactory.create()'), 'each Sync Controller must own an independent transport session')
assert.ok(!sync.includes('bluetoothConnected'), 'runtime connection state must never be persisted as Settings state')
assert.ok(syncTransport.includes('function createTransport()'), 'mock transport mutable timers must be instance scoped')
assert.ok(!syncTransport.startsWith('var connectTimer'), 'mock transport must not keep session timers at module scope')

assert.ok(settingsStore.includes("require('./store_core')"), 'Settings gateway wrapper must delegate concurrency to its executable core')
assert.ok(settingsStoreCore.includes('if (loading || loaded) return'), 'Settings initial storage read must be coalesced')
assert.ok(settingsStoreCore.includes('writeInFlight') && settingsStoreCore.includes('writeQueued'), 'Settings writes must be serialized')
assert.ok(settingsStoreCore.includes('if (!loaded) startLoad()'), 'early Settings updates must load persisted state before flushing')
assert.ok(!settingsStoreCore.includes('bluetoothConnected'), 'transient connection state must not regain persistent storage')

console.log('V2 wearable runtime contracts verified: resources have one owner, scoped generations and serialized persistence')
