const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const read = name => fs.readFileSync(path.join(root, name), 'utf8')

const clock = read('src/v2/features/clock/controller.js')
const workout = read('src/v2/features/workout/controller.js')
const notification = read('src/v2/features/notification/controller.js')
const eventGateway = read('src/capabilities/system_event.js')
const interconnectGateway = read('src/capabilities/interconnect.js')
const motionController = read('src/v2/features/settings/motion_controller.js')
const vibrationController = read('src/v2/features/settings/vibration_controller.js')
const haptics = read('src/v2/system/haptics.js')
const hapticsCore = read('src/v2/system/haptics_core.js')

assert.ok(clock.includes('powerRuntime.start()'), 'Clock start must activate the power runtime')
assert.ok(clock.includes('powerRuntime.stop()'), 'Clock stop must release the power runtime')
assert.ok(clock.includes('notification.start()') && clock.includes('notification.stop()'), 'Clock lifecycle must own its notification consumer')
assert.ok(clock.includes("historyRepository.saveToday(activityStore.getSnapshot()"), 'Clock lifecycle must persist semantic daily state without page-owned storage')

assert.ok(workout.includes('location.subscribe('), 'running workout must activate location only through the capability gateway')
assert.ok(workout.includes('location.unsubscribe('), 'workout pause/stop must release location')
assert.ok(workout.includes('setInterval('), 'running workout may own one session tick')
assert.ok(workout.includes('clearInterval('), 'workout lifecycle must release the session tick')
assert.ok(workout.includes('activityStore.addAndPersist('), 'workout finish must commit activity in feature orchestration')
assert.ok(workout.includes('historyRepository.saveToday('), 'workout finish must update seven-day history in feature orchestration')
assert.ok(workout.includes('workoutRepository.saveRecord('), 'workout finish must persist the workout record in feature orchestration')

assert.ok(notification.includes('systemEvent.subscribe(EVENT_NAME, onExternal)'), 'notification runtime must lazily subscribe to external events')
assert.ok(notification.includes('systemEvent.unsubscribe(EVENT_NAME, onExternal)'), 'notification runtime must release event subscription')
assert.ok(notification.includes('interconnect.subscribe(onExternal)'), 'notification runtime must lazily subscribe to interconnect')
assert.ok(notification.includes('interconnect.unsubscribe(onExternal)'), 'notification runtime must release interconnect')
assert.ok(notification.includes("HAPTIC_OWNER = 'notification'"), 'notification haptics must have an explicit lifecycle owner')
assert.ok(notification.includes('haptics.stop(HAPTIC_OWNER)'), 'notification dismiss must only stop its own haptic run')
assert.ok(eventGateway.includes('subscriptions.length'), 'system-event gateway must track active consumers')
assert.ok(interconnectGateway.includes('if (listeners.length === 0) disconnect()'), 'interconnect must disconnect after its final consumer')

assert.ok(motionController.includes('motion.subscribe('), 'motion diagnostics must consume the motion gateway')
assert.ok(motionController.includes('motion.unsubscribe('), 'motion diagnostics must release the motion gateway')
assert.ok(!motionController.includes('@system.sensor'), 'motion feature must never bypass its capability gateway')
assert.ok(motionController.includes("HAPTIC_OWNER = 'motion-diagnostics'"), 'motion haptics must have an explicit lifecycle owner')
assert.ok(motionController.includes('cancelMeasure()'), 'motion lifecycle must cancel one measurement generation before reset/stop')
assert.ok(motionController.includes('haptics.stop(HAPTIC_OWNER)'), 'motion stop must not cancel another Feature haptic run')

assert.ok(vibrationController.includes("HAPTIC_OWNER = 'settings-vibration'"), 'vibration settings must have an explicit haptic lifecycle owner')
assert.ok(vibrationController.includes('haptics.stop(HAPTIC_OWNER)'), 'vibration settings must only stop its own feedback')
assert.ok(vibrationController.includes("haptics.play(normalized, state.vibrationLevel, HAPTIC_OWNER) ? 'played' : 'unavailable'"), 'vibration feedback status must use the real execution result')

assert.ok(haptics.includes("require('./haptics_core')"), 'system haptics must delegate arbitration to its executable core')
assert.ok(hapticsCore.includes('activeOwner'), 'haptics runtime must track one physical executor owner')
assert.ok(hapticsCore.includes('generation !== expectedRun'), 'stale delayed pulses must be generation guarded')
assert.ok(hapticsCore.includes('activeOwner !== owner'), 'a stale consumer must not stop the current owner')

console.log('V2 wearable runtime contracts verified: resources have one owner, demand activation and scoped cleanup')
