const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const readJson = file => JSON.parse(fs.readFileSync(path.join(root, file), 'utf8'))
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

const appList = readJson('src/product/frontend/surfaces/applist.json')
const watchface = readJson('src/product/frontend/surfaces/watchface.json')
const brightness = readJson('src/product/frontend/surfaces/settings__brightness.json')
const settings = readJson('src/product/frontend/surfaces/settings__settings.json')
const history = readJson('src/product/frontend/surfaces/history.json')
const workout = readJson('src/product/frontend/surfaces/workout.json')
const today = readJson('src/product/frontend/surfaces/today.json')
const clock = readJson('src/product/frontend/surfaces/clock.json')
const collectionUx = read('src/components/surface_collection.ux')
const sliderUx = read('src/components/surface_slider.ux')
const honeycomb = read('src/product/frontend/engines/honeycomb.js')
const controllerRegistry = read('src/product/controller_registry.js')
const surfacePage = read('src/runtime/surface_page.js')
const designSkill = read('docs/VELA_WEARABLE_DESIGN_SKILL.md')

assert.ok(appList.experience, 'AppList must declare interaction experience in JSON')
assert.strictEqual(appList.experience.circle.collection.mode, 'honeycomb', 'Circle launcher must remain honeycomb')
assert.strictEqual(appList.experience.pill.collection.mode, 'paged-list', 'Pill launcher must remain paged list')
assert.strictEqual(appList.experience.rect.collection.mode, 'designed-grid', 'Rect launcher must remain designed grid')
const launcherItems = appList.experience.base.collection.items
assert.strictEqual(launcherItems.length, 12, 'Launcher parity requires the accepted 12 app entries')
launcherItems.forEach(item => {
  assert.ok(item.icon && item.icon.indexOf('/common/icons/') === 0, item.id + ' must retain visual icon')
  assert.ok(item.action && item.action.charAt(0) === '/', item.id + ' must retain navigation action')
})
const honeyTokens = appList.experience.circle.collection.tokens
;[
  'spacing', 'rowHeight', 'focusX', 'focusY', 'iconBase', 'iconGrow', 'radiusRatio', 'emphasisFalloff',
  'opacityBase', 'opacityEmphasis', 'avoidanceOpacity', 'elasticBase', 'elasticRange', 'elasticFalloff',
  'dragDamping', 'maxFrameDelta', 'frameMs', 'overscrollLimit', 'overscrollDamping', 'inertiaDecay',
  'minVelocity', 'magnetDistance', 'visibleMargin', 'labelCenterY', 'labelHalfHeight', 'labelHalfWidth',
  'movingLabelOpacity', 'snapDuration', 'dragThreshold', 'tapSuppressDuration', 'velocityPreviousWeight',
  'velocitySampleWeight', 'edgeBackDistance', 'edgeBackStart', 'edgeBackVerticalLimit'
].forEach(name => assert.strictEqual(typeof honeyTokens[name], 'number', 'L3 Honeycomb must author ' + name + ' in JSON'))
assert.ok(honeyTokens.inertiaDecay < 1, 'Honeycomb must declare inertia')
assert.ok(honeyTokens.magnetDistance > 0, 'Honeycomb must declare center snap')
assert.ok(collectionUx.includes('@touchstart="onHoneyStart"') && collectionUx.includes('startHoneyInertia'), 'Generic collection must implement direct honeycomb drag/inertia')
assert.ok(collectionUx.includes('@swipe="onSwipe"'), 'Generic collection must implement swipe pagination')
assert.ok(!/#[0-9a-f]{3,8}\b/i.test(collectionUx), 'Generic collection renderer must not own product colors')
assert.ok(!/pages\//.test(honeycomb), 'Generic honeycomb engine must not know product routes')
assert.ok(honeycomb.includes('requiredNumber(source.spacing'), 'Honeycomb engine must require authored JSON geometry instead of carrying a default design')
assert.ok(!/#[0-9a-f]{3,8}\b/i.test(honeycomb), 'Generic honeycomb engine must not own product colors')

assert.ok(watchface.experience, 'Watchface must declare its L3 selector experience in JSON')
assert.strictEqual(watchface.experience.circle.collection.mode, 'preview-swiper', 'Circle watchface selector must remain preview swiper')
assert.strictEqual(watchface.experience.pill.collection.mode, 'cards-pager', 'Pill watchface selector must remain preview-card pager')
assert.strictEqual(watchface.experience.rect.collection.mode, 'preview-grid', 'Rect watchface selector must remain preview grid')
const faceItems = watchface.experience.base.collection.items
assert.deepStrictEqual(faceItems.map(item => item.id), ['sport', 'simple', 'dashboard', 'mechanical', 'alpine'])
faceItems.forEach(item => {
  assert.ok(item.label && item.description && item.tag, item.id + ' presentation copy must remain JSON-owned')
  assert.ok(/^#[0-9A-Fa-f]{6}$/.test(item.background), item.id + ' preview background must remain JSON-owned')
  assert.ok(/^#[0-9A-Fa-f]{6}$/.test(item.accent), item.id + ' preview accent must remain JSON-owned')
  assert.strictEqual(item.action, 'watchface-select:' + item.id)
})
assert.deepStrictEqual(watchface.experience.circle.collection.itemIds, ['sport', 'simple', 'dashboard', 'mechanical'])
assert.deepStrictEqual(watchface.experience.pill.collection.itemIds, ['sport', 'simple', 'dashboard', 'alpine'])
assert.deepStrictEqual(watchface.experience.rect.collection.itemIds, ['sport', 'simple', 'dashboard'])
assert.ok(collectionUx.includes("model.mode === 'preview-swiper'") && collectionUx.includes('<swiper'), 'Generic collection must render the Circle watchface preview swiper')
assert.ok(collectionUx.includes("model.mode === 'cards-pager'"), 'Generic collection must render the Pill watchface preview-card pager')
assert.ok(collectionUx.includes("model.mode === 'preview-grid'"), 'Generic collection must render the Rect watchface preview grid')
assert.ok(collectionUx.includes('@click="activateItem($item)"'), 'Watchface previews must remain directly selectable')

assert.ok(brightness.experience, 'Brightness must declare direct-manipulation experience')
const slider = brightness.experience.base.sliders[0]
assert.strictEqual(slider.min, 0)
assert.strictEqual(slider.max, 255)
assert.strictEqual(slider.step, 1)
assert.strictEqual(slider.action, 'brightness-set')
assert.ok(sliderUx.includes('<slider'), 'Brightness parity requires a real slider primitive')
assert.ok(!brightness.modules.some(module => module.id === 'down' || module.id === 'up'), 'Brightness must not degrade the slider into +/- buttons')

assert.ok(settings.experience && settings.experience.base.collection, 'Settings must preserve its shared L1 pager in JSON')
assert.strictEqual(settings.experience.base.collection.mode, 'paged-list', 'Settings must remain swipe-paged instead of degrading to a long button list')
assert.strictEqual(settings.experience.base.collection.items.length, 5, 'Settings pager must preserve the five accepted entries')
assert.strictEqual(settings.experience.base.collection.tokens.pageItemCount, 3, 'Rect/default Settings keeps three items per page')
assert.strictEqual(settings.experience.circle.collection.mode, undefined, 'L1 Settings must not choose a Circle-specific interaction engine')
assert.strictEqual(settings.experience.circle.collection.tokens.pageItemCount, 2, 'Circle Settings keeps two items per page')
assert.strictEqual(settings.experience.pill.collection.mode, undefined, 'L1 Settings must not choose a Pill-specific interaction engine')
assert.strictEqual(settings.experience.pill.collection.tokens.pageItemCount, 3, 'Pill Settings keeps three items per page')
assert.strictEqual(settings.modules.length, 0, 'Settings must not render a second handwritten-style button list beside the shared pager')

const historyTrend = history.modules.find(module => module.id === 'trend')
assert.strictEqual(historyTrend.tokens.mode, 'columns', 'History shared baseline remains the column trend expression')
assert.strictEqual(history.variants.pill.modules.trend.mode, 'rows', 'L2 Pill History must retain its local row-trend expression')
const workoutMetrics = workout.modules.find(module => module.id === 'metrics')
assert.strictEqual(workoutMetrics.tokens.columns, 4, 'Workout Rect/default keeps its four-metric dashboard row')
assert.strictEqual(workout.variants.circle.modules.metrics.columns, 2, 'L2 Circle Workout keeps the compact two-column metric composition')
assert.strictEqual(workout.variants.pill.modules.metrics.columns, 2, 'L2 Pill Workout keeps the larger two-column metric composition')
const todaySummary = today.modules.find(module => module.id === 'summaryMetrics')
const todayCalendar = today.modules.find(module => module.id === 'calendarGrid')
assert.strictEqual(todaySummary.tokens.columns, 2, 'Today keeps shared summary semantics')
assert.ok(today.variants.circle.modules.summaryMetrics.height < todaySummary.tokens.height, 'L2 Circle Today must retain the compact summary expression')
assert.ok(today.variants.pill.modules.calendarGrid.itemHeight > todayCalendar.tokens.itemHeight, 'L2 Pill Today must retain the expanded month-calendar expression')

assert.ok(clock.experience && clock.experience.base.gestures, 'Clock gestures must be declared in JSON')
assert.strictEqual(clock.experience.base.gestures.up, '/pages/applist')
assert.strictEqual(clock.experience.base.gestures.left, 'clock-next-face')
assert.strictEqual(clock.experience.base.gestures.right, 'clock-prev-face')
assert.strictEqual(clock.experience.base.gestures.longpress, '/pages/watchface')
assert.deepStrictEqual(clock.experience.circle.controllerConfig.faceIds, ['sport', 'simple', 'dashboard', 'mechanical'])
assert.deepStrictEqual(clock.experience.pill.controllerConfig.faceIds, ['sport', 'simple', 'dashboard', 'alpine'])
assert.deepStrictEqual(clock.experience.rect.controllerConfig.faceIds, ['sport', 'simple', 'dashboard'])
assert.ok(surfacePage.includes('page.surfacePlan.controllerConfig'), 'Resolved JSON controller configuration must cross the generic Surface Page boundary')
assert.ok(controllerRegistry.includes('controllerConfig.faceIds'), 'Controller registry must require JSON-authored face availability')
assert.ok(!/var\s+FACE_IDS\s*=/.test(controllerRegistry), 'Controller registry must not own a duplicate watchface availability list')
assert.ok(controllerRegistry.includes('navigation.back()'), 'Selecting a watchface must preserve the accepted return-to-clock interaction')

assert.ok(designSkill.includes('A migration is incomplete if functionality or interaction quality is reduced'), 'Wearable design contract must explicitly ban interaction regression')
console.log('V3 interaction parity verified: L1 shared controls, L2 local expressions and L3 independent surfaces preserve accepted behavior')
