const assert = require('assert')
const fs = require('fs')
const path = require('path')

const root = path.resolve(__dirname, '..')
const readJson = file => JSON.parse(fs.readFileSync(path.join(root, file), 'utf8'))
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

const appList = readJson('src/product/frontend/surfaces/applist.json')
const watchface = readJson('src/product/frontend/surfaces/watchface.json')
const brightness = readJson('src/product/frontend/surfaces/settings__brightness.json')
const settings = readJson('src/product/frontend/surfaces/settings__settings.json')
const vibration = readJson('src/product/frontend/surfaces/settings__vibration.json')
const motion = readJson('src/product/frontend/surfaces/settings__motion.json')
const diagnostics = readJson('src/product/frontend/surfaces/settings__diagnostics.json')
const history = readJson('src/product/frontend/surfaces/history.json')
const workout = readJson('src/product/frontend/surfaces/workout.json')
const today = readJson('src/product/frontend/surfaces/today.json')
const clock = readJson('src/product/frontend/surfaces/clock.json')
const collectionUx = read('src/components/surface_collection.ux')
const sliderUx = read('src/components/surface_slider.ux')
const honeycomb = read('src/product/frontend/engines/honeycomb.js')
const controllerRegistry = read('src/product/controller_registry.js')
const surfacePage = read('src/runtime/surface_page.js')
const designSkill = read('docs/VELA_WEARABLE_DESIGN_SKILL.md')

assert.ok(appList.experience, 'AppList must declare interaction experience in JSON')
assert.strictEqual(appList.experience.circle.collection.mode, 'honeycomb', 'Circle launcher must remain honeycomb')
assert.strictEqual(appList.experience.pill.collection.mode, 'paged-list', 'Pill launcher must remain paged list')
assert.strictEqual(appList.experience.rect.collection.mode, 'designed-grid', 'Rect launcher must remain designed grid')
const launcherItems = appList.experience.base.collection.items
assert.strictEqual(launcherItems.length, 12, 'Launcher parity requires the accepted 12 app entries')
launcherItems.forEach(item => {
  assert.ok(item.icon && item.icon.indexOf('/common/icons/') === 0, item.id + ' must retain visual icon')
  assert.ok(item.action && item.action.charAt(0) === '/', item.id + ' must retain navigation action')
})
const honeyTokens = appList.experience.circle.collection.tokens
;[
  'spacing', 'rowHeight', 'focusX', 'focusY', 'iconBase', 'iconGrow', 'radiusRatio', 'emphasisFalloff',
  'opacityBase', 'opacityEmphasis', 'avoidanceOpacity', 'elasticBase', 'elasticRange', 'elasticFalloff',
  'dragDamping', 'maxFrameDelta', 'frameMs', 'overscrollLimit', 'overscrollDamping', 'inertiaDecay',
  'minVelocity', 'magnetDistance', 'visibleMargin', 'labelCenterY', 'labelHalfHeight', 'labelHalfWidth',
  'movingLabelOpacity', 'snapDuration', 'dragThreshold', 'tapSuppressDuration', 'velocityPreviousWeight',
  'velocitySampleWeight', 'edgeBackDistance', 'edgeBackStart', 'edgeBackVerticalLimit'
].forEach(name => assert.strictEqual(typeof honeyTokens[name], 'number', 'L3 Honeycomb must author ' + name + ' in JSON'))
assert.ok(honeyTokens.inertiaDecay < 1, 'Honeycomb must declare inertia')
assert.ok(honeyTokens.magnetDistance > 0, 'Honeycomb must declare center snap')
assert.ok(collectionUx.includes('@touchstart="onHoneyStart"') && collectionUx.includes('startHoneyInertia'), 'Generic collection must implement direct honeycomb drag/inertia')
assert.ok(collectionUx.includes('@swipe="onSwipe"'), 'Generic collection must implement swipe pagination')
assert.ok(!/#[0-9a-f]{3,8}\b/i.test(collectionUx), 'Generic collection renderer must not own product colors')
assert.ok(!/pages\//.test(honeycomb), 'Generic honeycomb engine must not know product routes')
assert.ok(honeycomb.includes('requiredNumber(source.spacing'), 'Honeycomb engine must require authored JSON geometry instead of carrying a default design')
assert.ok(!/#[0-9a-f]{3,8}\b/i.test(honeycomb), 'Generic honeycomb engine must not own product colors')

assert.ok(watchface.experience, 'Watchface must declare its L3 selector experience in JSON')
assert.strictEqual(watchface.experience.circle.collection.mode, 'preview-swiper', 'Circle watchface selector must remain preview swiper')
assert.strictEqual(watchface.experience.pill.collection.mode, 'cards-pager', 'Pill watchface selector must remain preview-card pager')
assert.strictEqual(watchface.experience.rect.collection.mode, 'preview-grid', 'Rect watchface selector must remain preview grid')
const faceItems = watchface.experience.base.collection.items
assert.deepStrictEqual(faceItems.map(item => item.id), ['sport', 'simple', 'dashboard', 'mechanical', 'alpine'])
faceItems.forEach(item => {
  assert.ok(item.label && item.description && item.tag, item.id + ' presentation copy must remain JSON-owned')
  assert.ok(/^#[0-9A-Fa-f]{6}$/.test(item.background), item.id + ' preview background must remain JSON-owned')
  assert.ok(/^#[0-9A-Fa-f]{6}$/.test(item.accent), item.id + ' preview accent must remain JSON-owned')
  assert.strictEqual(item.action, 'watchface-select:' + item.id)
})
assert.deepStrictEqual(watchface.experience.circle.collection.itemIds, ['sport', 'simple', 'dashboard', 'mechanical'])
assert.deepStrictEqual(watchface.experience.pill.collection.itemIds, ['sport', 'simple', 'dashboard', 'alpine'])
assert.deepStrictEqual(watchface.experience.rect.collection.itemIds, ['sport', 'simple', 'dashboard'])
assert.ok(collectionUx.includes("model.mode === 'preview-swiper'") && collectionUx.includes('<swiper'), 'Generic collection must render the Circle watchface preview swiper')
assert.ok(collectionUx.includes("model.mode === 'cards-pager'"), 'Generic collection must render the Pill watchface preview-card pager')
assert.ok(collectionUx.includes("model.mode === 'preview-grid'"), 'Generic collection must render the Rect watchface preview grid')
assert.ok(collectionUx.includes('@click="activateItem($item)"'), 'Watchface previews must remain directly selectable')

assert.ok(brightness.experience, 'Brightness must declare direct-manipulation experience')
const slider = brightness.experience.base.sliders[0]
assert.strictEqual(slider.min, 0)
assert.strictEqual(slider.max, 255)
assert.strictEqual(slider.step, 1)
assert.strictEqual(slider.action, 'brightness-set')
assert.ok(sliderUx.includes('<slider'), 'Brightness parity requires a real slider primitive')
assert.ok(!brightness.modules.some(module => module.id === 'down' || module.id === 'up'), 'Brightness must not degrade the slider into +/- buttons')

assert.ok(settings.experience && settings.experience.base.collection, 'Settings must preserve its shared L1 pager in JSON')
assert.strictEqual(settings.experience.base.collection.mode, 'paged-list', 'Settings must remain swipe-paged instead of degrading to a long button list')
assert.strictEqual(settings.experience.base.collection.items.length, 5, 'Settings pager must preserve the five accepted entries')
assert.strictEqual(settings.experience.base.collection.tokens.pageItemCount, 3, 'Rect/default Settings keeps three items per page')
assert.strictEqual(settings.experience.circle.collection.mode, undefined, 'L1 Settings must not choose a Circle-specific interaction engine')
assert.strictEqual(settings.experience.circle.collection.tokens.pageItemCount, 2, 'Circle Settings keeps two items per page')
assert.strictEqual(settings.experience.pill.collection.mode, undefined, 'L1 Settings must not choose a Pill-specific interaction engine')
assert.strictEqual(settings.experience.pill.collection.tokens.pageItemCount, 3, 'Pill Settings keeps three items per page')
assert.strictEqual(settings.modules.length, 0, 'Settings must not render a second handwritten-style button list beside the shared pager')

const vibrationById = Object.fromEntries(vibration.modules.map(module => [module.id, module]))
assert.strictEqual(vibration.initialState.enabled, 'loading', 'Vibration first frame must not fabricate enabled/disabled business truth')
assert.strictEqual(vibration.initialState.controlsOpen, false, 'Vibration controls stay hidden until the settings controller returns truth')
assert.strictEqual(vibrationById.toggle.visibleWhen, 'controlsOpen', 'Vibration controls must remain on page 1')
assert.strictEqual(vibrationById.patternTap.visibleWhen, 'patternsOpen', 'Vibration patterns must remain on page 2')
assert.strictEqual(vibrationById.pageNext.actions.tap, 'vibration-page:patterns')
assert.strictEqual(vibrationById.pagePrevious.actions.tap, 'vibration-page:controls')
assert.ok(vibration.experience && vibration.experience.base.collection, 'Vibration strength must be a declarative generic control')
assert.strictEqual(vibration.experience.base.collection.mode, 'segmented', 'Vibration strength must remain a horizontal segmented control')
assert.strictEqual(vibration.experience.base.collection.bind.selectedId, 'level')
assert.deepStrictEqual(vibration.experience.base.collection.items.map(item => item.id), ['light', 'medium', 'strong'])
assert.ok(vibration.experience.base.collection.items.every(item => item.action === 'vibration-level:' + item.id), 'Segment actions must stay JSON-owned')
assert.ok(!vibrationById.levelLight && !vibrationById.levelMedium && !vibrationById.levelStrong, 'Vibration must not regress to three vertical strength buttons')
assert.ok(collectionUx.includes("model.mode === 'segmented'") && collectionUx.includes('buildSegmented'), 'Generic collection must implement reusable segmented selection')
assert.ok(controllerRegistry.includes("name === 'vibration-page:patterns'") && controllerRegistry.includes("name === 'vibration-page:controls'"), 'Vibration semantic adapter must preserve two-page navigation without visual constants')

const motionById = Object.fromEntries(motion.modules.map(module => [module.id, module]))
assert.strictEqual(motion.initialState.sensorStatus, 'loading', 'Motion first frame must not fabricate sensor availability')
assert.strictEqual(motion.initialState.diagnosticsOpen, false, 'Motion diagnostics stay hidden until the controller returns truth')
assert.strictEqual(motionById.axes.visibleWhen, 'diagnosticsOpen', 'Motion live diagnostics must remain on page 1')
assert.strictEqual(motionById.measureState.visibleWhen, 'measureOpen', 'Motion action measurement must remain on page 2')
assert.strictEqual(motionById.diagnosticsNext.actions.tap, 'motion-page:measure')
assert.strictEqual(motionById.measurePrevious.actions.tap, 'motion-page:diagnostics')
assert.ok(controllerRegistry.includes("name === 'motion-page:measure'") && controllerRegistry.includes("name === 'motion-page:diagnostics'"), 'Motion semantic adapter must preserve two-page navigation without visual constants')

const diagnosticsById = Object.fromEntries(diagnostics.modules.map(module => [module.id, module]))
assert.strictEqual(diagnostics.initialState.ready, false, 'Diagnostics first frame must wait for resolved device truth')
assert.strictEqual(diagnosticsById.device.visibleWhen, 'deviceOpen', 'Diagnostics page 1 must remain the device profile')
assert.strictEqual(diagnosticsById.capabilities.visibleWhen, 'capabilitiesOpen', 'Diagnostics later pages must remain capability pages')
assert.strictEqual(diagnosticsById.capabilities.bind.items, 'capabilityPage', 'Diagnostics must page semantic capability data instead of rendering one long grid')
assert.strictEqual(diagnostics.experience.base.collection.mode, 'segmented', 'Diagnostics must keep a compact reusable pager control')
assert.deepStrictEqual(diagnostics.experience.base.collection.items.map(item => item.action), ['diagnostics-page:previous', 'diagnostics-page:next'])
assert.strictEqual(diagnostics.experience.base.gestures.left, 'diagnostics-page:next', 'Diagnostics must support forward swipe paging')
assert.strictEqual(diagnostics.experience.base.gestures.right, 'diagnostics-page:previous', 'Diagnostics must support backward swipe paging')
assert.strictEqual(diagnostics.experience.base.controllerConfig.capabilityPageSize, 4, 'Diagnostics semantic page size stays shared below L3')
assert.strictEqual(diagnostics.experience.circle.controllerConfig, undefined, 'Circle L1 diagnostics must not override semantic controller configuration')
assert.strictEqual(diagnostics.experience.pill.controllerConfig, undefined, 'Pill L1 diagnostics must not override semantic controller configuration')
assert.ok(controllerRegistry.includes("name === 'diagnostics-page:next'") && controllerRegistry.includes('config.capabilityPageSize'), 'Diagnostics adapter must consume JSON paging configuration and semantic paging actions')

const historyTrend = history.modules.find(module => module.id === 'trend')
assert.strictEqual(historyTrend.tokens.mode, 'columns', 'History shared baseline remains the column trend expression')
assert.strictEqual(history.variants.pill.modules.trend.mode, 'rows', 'L2 Pill History must retain its local row-trend expression')
const workoutMetrics = workout.modules.find(module => module.id === 'metrics')
assert.strictEqual(workoutMetrics.tokens.columns, 4, 'Workout Rect/default keeps its four-metric dashboard row')
assert.strictEqual(workout.variants.circle.modules.metrics.columns, 2, 'L2 Circle Workout keeps the compact two-column metric composition')
assert.strictEqual(workout.variants.pill.modules.metrics.columns, 2, 'L2 Pill Workout keeps the larger two-column metric composition')
const todaySummary = today.modules.find(module => module.id === 'summaryMetrics')
const todayCalendar = today.modules.find(module => module.id === 'calendarGrid')
assert.strictEqual(todaySummary.tokens.columns, 2, 'Today keeps shared summary semantics')
assert.ok(today.variants.circle.modules.summaryMetrics.height < todaySummary.tokens.height, 'L2 Circle Today must retain the compact summary expression')
assert.ok(today.variants.pill.modules.calendarGrid.itemHeight > todayCalendar.tokens.itemHeight, 'L2 Pill Today must retain the expanded month-calendar expression')

assert.ok(clock.experience && clock.experience.base.gestures, 'Clock gestures must be declared in JSON')
assert.strictEqual(clock.experience.base.gestures.up, '/pages/applist')
assert.strictEqual(clock.experience.base.gestures.left, 'clock-next-face')
assert.strictEqual(clock.experience.base.gestures.right, 'clock-prev-face')
assert.strictEqual(clock.experience.base.gestures.longpress, '/pages/watchface')
assert.deepStrictEqual(clock.experience.circle.controllerConfig.faceIds, ['sport', 'simple', 'dashboard', 'mechanical'])
assert.deepStrictEqual(clock.experience.pill.controllerConfig.faceIds, ['sport', 'simple', 'dashboard', 'alpine'])
assert.deepStrictEqual(clock.experience.rect.controllerConfig.faceIds, ['sport', 'simple', 'dashboard'])
assert.ok(surfacePage.includes('page.surfacePlan.controllerConfig'), 'Resolved JSON controller configuration must cross the generic Surface Page boundary')
assert.ok(controllerRegistry.includes('controllerConfig.faceIds'), 'Controller registry must require JSON-authored face availability')
assert.ok(!/var\s+FACE_IDS\s*=/.test(controllerRegistry), 'Controller registry must not own a duplicate watchface availability list')
assert.ok(controllerRegistry.includes('navigation.back(ownerKey(owner))'), 'Selecting a watchface must preserve the accepted return-to-clock interaction')
assert.ok(controllerRegistry.includes('ownerCurrent(owner, token)'), 'Async return-to-clock must not navigate after the selector page loses ownership')

assert.ok(designSkill.includes('A migration is incomplete if functionality or interaction quality is reduced'), 'Wearable design contract must explicitly ban interaction regression')
console.log('V3 interaction parity verified: L1 direct manipulation/paging, L2 local expressions and L3 independent surfaces preserve accepted behavior')
