const assert = require('assert')
const fs = require('fs')
const path = require('path')
const childProcess = require('child_process')

const root = path.resolve(__dirname, '..')
const generatedFile = path.join(root, 'src', 'product', 'frontend', 'generated', 'watchface_previews.js')
const compileFile = path.join(root, 'scripts', 'compile-v3-surfaces.js')
const watchfaceFile = path.join(root, 'src', 'product', 'frontend', 'surfaces', 'watchface.json')

childProcess.execFileSync(process.execPath, [compileFile], { cwd: root, stdio: 'pipe' })
delete require.cache[require.resolve(generatedFile)]
const generated = require(generatedFile)
const clockSurface = require('../src/product/frontend/surfaces/clock.json')
const watchfaceSurface = require('../src/product/frontend/surfaces/watchface.json')
const previewCompiler = require('../scripts/lib/watchface-preview-compiler')
const sceneRuntime = require('../src/product/design/scene')
const surfaceRuntime = require('../src/product/frontend/runtime/surface_runtime')
const experienceRuntime = require('../src/product/frontend/runtime/experience_runtime')

const expected = previewCompiler.compile(clockSurface, watchfaceSurface, {
  scene: sceneRuntime,
  surfaceRuntime: surfaceRuntime,
  experienceRuntime: experienceRuntime
})
assert.deepStrictEqual(generated.previewsById, expected, 'tracked/generated watchface preview data must be a pure compile result of Clock stage IR')

const allowed = {
  circle: ['sport', 'simple', 'dashboard', 'mechanical'],
  pill: ['sport', 'simple', 'dashboard', 'alpine'],
  rect: ['sport', 'simple', 'dashboard']
}
Object.keys(allowed).forEach(function (shape) {
  allowed[shape].forEach(function (faceId) {
    const preview = generated.previewsById[faceId] && generated.previewsById[faceId][shape]
    assert.ok(preview, shape + '/' + faceId + ' must have a generated preview')
    assert.ok(preview.width > 0 && preview.height > 0, shape + '/' + faceId + ' preview must own explicit target size')
    assert.ok(Array.isArray(preview.boxes) && Array.isArray(preview.texts), shape + '/' + faceId + ' preview must use generated primitive IR')
    assert.ok(preview.boxes.length + preview.texts.length > 0, shape + '/' + faceId + ' preview must not be an empty color swatch')
  })
})
assert.ok(!generated.previewsById.mechanical.pill && !generated.previewsById.mechanical.rect, 'Mechanical preview must stay Circle-only like Clock')
assert.ok(!generated.previewsById.alpine.circle && !generated.previewsById.alpine.rect, 'Alpine preview must stay Pill-only like Clock')

const mechanical = generated.previewsById.mechanical.circle
assert.ok(mechanical.boxes.filter(item => /^tick-/.test(item.id)).length >= 60, 'Mechanical preview must preserve the authored Clock tick structure')
assert.ok(mechanical.boxes.some(item => /^hand-/.test(item.id) && /^rotate\(/.test(item.transform)), 'Mechanical preview must preserve generated analog hands')
const circleSignatures = allowed.circle.map(function (faceId) { return JSON.stringify(generated.previewsById[faceId].circle) })
assert.strictEqual(new Set(circleSignatures).size, circleSignatures.length, 'Circle faces must not collapse back to one generic preview template')

const generatedSource = fs.readFileSync(generatedFile, 'utf8')
assert.ok(generatedSource.startsWith('// AUTO-GENERATED by scripts/compile-v3-surfaces.js.'), 'preview data must remain compiler-owned')
assert.ok(!/\brequire\s*\(/.test(generatedSource), 'generated preview data must not pull Clock or other Surface JSON at runtime')
const collectionSource = fs.readFileSync(path.join(root, 'src', 'components', 'surface_collection.ux'), 'utf8')
assert.ok(collectionSource.includes('<surfacepreview'), 'watchface collection modes must render generated preview IR')
assert.ok(!collectionSource.includes('previewTimeText'), 'Circle/Rect selector must not render the old fixed 08:32 token')
assert.ok(!collectionSource.includes('previewHourText') && !collectionSource.includes('previewMinuteText'), 'Pill selector must not render the old fixed hour/minute template')

const watchfaceSource = fs.readFileSync(watchfaceFile, 'utf8')
;['previewTimeText', 'previewTimeSize', 'previewTimeWeight', 'previewHourText', 'previewHourSize', 'previewHourWeight', 'previewMinuteText', 'previewMinuteSize', 'previewMinuteColor', 'previewMinuteWeight'].forEach(function (token) {
  assert.ok(!watchfaceSource.includes('"' + token + '"'), 'Watchface Surface must not retain dead fixed-time preview token ' + token)
})

const runtimeSurface = generated.attach(JSON.parse(JSON.stringify(watchfaceSurface)))
function circleCollection(selectedId) {
  return experienceRuntime.decorate({}, runtimeSurface, { formFactor: 'circle' }, { width: 192, height: 192 }, { left: 0, top: 0, width: 192, height: 192 }, { selectedId: selectedId }).collection
}
function hasSelectionIndicator(item) {
  return !!(item && item.preview && item.preview.boxes && item.preview.boxes.some(function (box) { return box.id === 'selection-indicator' }))
}
const sportSelected = circleCollection('sport')
assert.ok(hasSelectionIndicator(sportSelected.items.find(item => item.id === 'sport')), 'selected Circle face must expose an authored preview selection indicator')
assert.ok(!hasSelectionIndicator(sportSelected.items.find(item => item.id === 'simple')), 'unselected Circle face must not expose the selection indicator')
const simpleSelected = circleCollection('simple')
assert.ok(!hasSelectionIndicator(simpleSelected.items.find(item => item.id === 'sport')), 'selection indicator must leave the previously selected face')
assert.ok(hasSelectionIndicator(simpleSelected.items.find(item => item.id === 'simple')), 'selection indicator must follow selectedId changes')

const pageSource = fs.readFileSync(path.join(root, 'src', 'pages', 'watchface', 'index.ux'), 'utf8')
assert.ok(pageSource.includes("require('../../product/frontend/surfaces/watchface.json')"), 'Watchface page must keep its one authored Surface dependency')
assert.ok(pageSource.includes("require('../../product/frontend/generated/watchface_previews')"), 'Watchface page must load only its page-local generated preview data')

console.log('Watchface preview truth verified: Clock-derived previews preserve face identity, selected state and no fixed-time mock tokens')
